### ISSUE TITLE
Out of memory on huge amount of records

### ISSUE THREAD

**Issue by rkoblev** [edasque/DynamoDBtoCSV#28]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

It happens on huge amount of records. In my case about 4 million records

**Comment by edasque** [comment]
Sorry, can't help there, I don't have a DynamoDB db anymore.

**Comment by tcchau** [comment]
@rkoblev This happens because the change I made to deal with inconsistent "schema" in the table means that the code has to look at all the data first before being able to determine what the headers are. I can create a mode of operation for when you have a fixed schema that can avoid the large database problem, if you're still interested in this. Please write back if you are.

**Comment by rkoblev** [comment]
@tcchau Thanks, but I'm not interested anymore. It was one time job

**Comment by kashalkar** [comment]
Got the same error as @rkoblev with around 800K records.
@tcchau - It would be good to have another mode of operation as you suggest.

**Comment by thirstyfish** [comment]
Same issue here

**Comment by Zhang21** [comment]
same problem：`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by Zhang21** [comment]
The method is increase node limit memory, because default limit memory of node is not enough.

```bash
# 2GB(2048MB)
node --max-old-space-size=2048 xxx.js
```
