### ISSUE TITLE
Dummy line

### ISSUE THREAD

**Issue by MarcoPorracin** [edasque/DynamoDBtoCSV#31]
Im getting a 'dummy' line, how can i avoid this from happening?

**Comment by edasque** [comment]
What do you mean, can you run the command and copy out the input and output here?

**Comment by MarcoPorracin** [comment]
I run:

`node dynamoDBtoCSV.js -t TableName > result.csv`

And on the csv i see:

![get](https://user-images.githubusercontent.com/22181136/37101344-1a63994c-2204-11e8-9e4b-2ffb1a3cc5fa.png)

But this 'dummy' line isn't on my dynamoDB its added by the code.

**Comment by edasque** [comment]
@tcchau can you speak to that? Seems that line wasn't unmarshalled correctly, causing dummy rows to be inserted in its place?

**Comment by tcchau** [comment]
@edasque @MarcoPorracin Hi there. Yes, sorry, I didn't have enough time to solve the original problem completely.

Let me explain: The original problem is that if you have a table that uses a variable set of attributes for items, and the first item that is retrieved by dynamoDBtoCSV will define the set of attributes that will be output. That is, if some of your items have an attribute called, 'optionalData', but not the first item, then 'optionalData' from any other item will not be included in the output.

The fastest way for me to resolve this problem was to create a dummy first item that contains every possible attribute that exists in any item in the whole table. 

The proper fix would have been to fix the output generation code so that it is aware that we're working with a items that may contain additional attributes.

If I have time later on this month, I can work on that, but if someone else can get to it first, by all means!

**Comment by edasque** [comment]
So @tcchau that line just has to be excluded from the CSV output (or just removed from that doc)?

**Comment by tcchau** [comment]
Yes, @edasque, I just remove it from my CSV output file manually, since I only occasionally run such a report.

**Comment by tcchau** [comment]
@MarcoPorracin @edasque It turns out, upon reviewing the papaparse library [documentation](https://www.papaparse.com/docs#json-to-csv) a little more closely, there's a way to eliminate the need for the dummy row fairly easily. I've issued a pull request to fix this #32

**Comment by MarcoPorracin** [comment]
Fixed on pull request #32
